require("ml.impatient")
require("ml.plugins")
require("ml.notify")
require("ml.options")
require("ml.keymaps")
require("ml.colorscheme")

require("ml.autocommands")
require("ml.lsp")
require("ml.luasnip")
require("ml.cmp")
require("ml.treesitter")
require("ml.telescope")

require("ml.nvim-tree")
require("ml.lualine")
require("ml.toggleterm")
require("ml.alpha")
require("ml.whichkey")
require("ml.nvim-colorizer")
require("ml.tailwindcss-colorizer-cmp")

require("ml.autopairs")
require("ml.comment")
require("ml.gitsigns")
require("ml.bufferline")
require("ml.project")
require("ml.indentline")

require("ml.python_init")
require("ml.rust-tools")
require("ml.nvim-dap")

-- require("ml.vimtex")

-- Custom plugins
-- require("ml.my_plugins.onSaveAction")
-- require("ml.my_plugins.diag_show")
require("ml.my_plugins.rust_sqlx_parser")
-- require("ml.my_plugins.rust_html_parser")
