#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/down.jpg
fi

leftwm-command "UnloadTheme"

pkill picom
pkill polybar
kill $(ps aux | grep "layout.sh" | grep -v grep | awk '{print $2}')
