#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" || exit ; pwd -P )"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s "${SCRIPTPATH}"/down /tmp/leftwm-theme-down

#boot a polybar for each monitor
index=0
monitors="$(polybar -m | sed s/:.*//)"
leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  let indextemp=index+1
  monitor=$(sed "$indextemp!d" <<<"$monitors")
  monitor=$monitor offset=$x width=$width polybar -c "$SCRIPTPATH"/polybar/config.ini &> /dev/null &
  let index=indextemp
done

#boot picom if it exists
if [ -x "$(command -v picom -b)" ]; then
  picom &> /dev/null &
fi

# set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# set the background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale "${SCRIPTPATH}/background.jpg"
fi

# start flameshot if exists
if [ -x "$(command -v flameshot)" ]; then
  flameshot &> /dev/null &
fi

echo "done"

