theme = "tokyonight"

[editor]
line-number = "relative"
auto-format = true
auto-completion = true
auto-save = true
true-color = true
# buffer-line = "multiple"
color-modes = true
mouse = true

[editor.statusline]
left = ["mode", "spinner", "diagnostics", "file-encoding", "separator", "file-line-ending", "separator", "file-type", "separator", "file-name"]
center = []
right = [ "selections", "separator" , "position", "position-percentage", "separator", "total-line-numbers"]
separator = "|"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "╎"

[editor.file-picker]
hidden = false

[keys.normal]
"backspace" = {f = ":fmt", r = ":sh cargo run", R = ":sh cargo run --release", t = ":sh cargo test", s = ":w", o = ":config-open", r = ":config-reload"}

[keys.insert]
"C-space" = "completion"
