[[language]]
name = "rust"
auto-format = true

[language.config]
checkOnSave = { command = "clippy" }

[language.debugger]
command = "codelldb"
name = "codelldb"
port-arg = "--port {}"
transport = "tcp"

[[language.debugger.templates]]
name = "binary"
request = "launch"

[[language.debugger.templates.completion]]
completion = "filename"
name = "binary"

[language.debugger.templates.args]
program = "{0}"
runInTerminal = true
[[language]]
name = "python"
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = true

[[language]]
name = "markdown"
language-server = { command = "ltex-ls" }
config = {additionalRules= {languageModel = "~/ngrams/"}}
file-types = ["md"]
scope = "source.markdown"
roots = []

[[language]]
name = "latex"
auto-format = true

[language.config.texlab.build]
onSave = true
forwardSearchAfter = true

[language.config.texlab.forwardSearch]
executable = "zathura"
args = [ "--synctex-forward", "%l:1:%f", "%p" ]

# [language.config.texlab.chktex]
# onEdit = true
